baseURL = "https://terra.mcfredrick.dev/"
title = "Terra"
languageCode = "en-us"
theme = "terra"
paginate = 20

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[params]
  description = "Daily climate & sustainability tech digest for engineers"
  author = "Terra Bot"

[markup]
  [markup.highlight]
    noClasses = false
